// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmvYOV2DiYUiO_dxRTriRVUiPT7iK1Rc',
    appId: '1:547656810736:web:76e0a821f8d92a4e454235',
    messagingSenderId: '547656810736',
    projectId: 'hemocell-5b31f',
    authDomain: 'hemocell-5b31f.firebaseapp.com',
    storageBucket: 'hemocell-5b31f.appspot.com',
    measurementId: 'G-0EYEZ9YHRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdp3TPOZWEuNOeQkvOxpMm3ErgNG-e5w',
    appId: '1:547656810736:android:f1de0de2e9e11729454235',
    messagingSenderId: '547656810736',
    projectId: 'hemocell-5b31f',
    storageBucket: 'hemocell-5b31f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkpSz2DXRhdw9KYeCZb8jPdgZQImAwfts',
    appId: '1:547656810736:ios:aaaa870474a0397b454235',
    messagingSenderId: '547656810736',
    projectId: 'hemocell-5b31f',
    storageBucket: 'hemocell-5b31f.appspot.com',
    iosBundleId: 'com.example.hemoCell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkpSz2DXRhdw9KYeCZb8jPdgZQImAwfts',
    appId: '1:547656810736:ios:aaaa870474a0397b454235',
    messagingSenderId: '547656810736',
    projectId: 'hemocell-5b31f',
    storageBucket: 'hemocell-5b31f.appspot.com',
    iosBundleId: 'com.example.hemoCell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMmvYOV2DiYUiO_dxRTriRVUiPT7iK1Rc',
    appId: '1:547656810736:web:e5192c630a446722454235',
    messagingSenderId: '547656810736',
    projectId: 'hemocell-5b31f',
    authDomain: 'hemocell-5b31f.firebaseapp.com',
    storageBucket: 'hemocell-5b31f.appspot.com',
    measurementId: 'G-N25VFFN0KG',
  );
}
